/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#a73a00",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005226",
        "secondary-fixed-dim": "#00e475",
        tertiary: "#5f5e5e",
        outline: "#8f7065",
        "on-primary-fixed-variant": "#802a00",
        "on-primary-fixed": "#370e00",
        "on-background": "#1b1c1c",
        "surface-tint": "#a73a00",
        "surface-container-highest": "#e3e2e2",
        "inverse-primary": "#ffb59a",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#3fff8b",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-container": "#007237",
        secondary: "#006d35",
        "on-tertiary-fixed-variant": "#474746",
        "error-container": "#ffdad6",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9f9",
        "on-secondary-fixed": "#00210b",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dbdad9",
        background: "#fbf9f9",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1c",
        error: "#ba1a1a",
        "primary-fixed-dim": "#ffb59a",
        "primary-container": "#ff5c00",
        "outline-variant": "#e4beb1",
        "tertiary-container": "#949292",
        "on-surface-variant": "#5b4137",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-container": "#521800",
        "on-tertiary-container": "#2c2b2b",
        "primary-fixed": "#ffdbce",
        "secondary-fixed": "#62ff96",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-variant": "#e3e2e2",
        "surface-container-high": "#e9e8e7",
        surface: "#fbf9f9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        pop: "4px",
      },
      spacing: {
        sm: "16px",
        xl: "64px",
        "margin-desktop": "32px",
        xs: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        base: "4px",
        md: "24px",
        lg: "40px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "technical-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "technical-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
      },
      borderWidth: {
        thick: "2px",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideUp: { "0%": { opacity: "0", transform: "translateY(40px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        pulse2: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.4" } },
        scanline: { "0%": { transform: "translateY(-100%)" }, "100%": { transform: "translateY(100vh)" } },
        float: { "0%, 100%": { transform: "translateY(0px) rotate(-8deg)" }, "50%": { transform: "translateY(-12px) rotate(-8deg)" } },
        float2: { "0%, 100%": { transform: "translateY(0px) rotate(6deg)" }, "50%": { transform: "translateY(-8px) rotate(6deg)" } },
      },
      animation: {
        fadeIn: "fadeIn 0.5s ease forwards",
        slideUp: "slideUp 0.6s ease forwards",
        pulse2: "pulse2 2s ease-in-out infinite",
        scanline: "scanline 2s linear infinite",
        float: "float 4s ease-in-out infinite",
        float2: "float2 5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
